### PR TITLE
Update Place Usa

### PR DESCRIPTION
**Pull request by missinglink**
Updating `data/858/854/17/85885417.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by missinglink** [comment]
I'm not familiar with this place but it seems incorrect that all other names for the place are some form of 'Mobile'

**Comment by stepps00** [comment]
Good catch! This is a weird one, I think what's happening here is:

- This record represents the "University of South Alabama" (USA) neighbourhood
- This record has a bunk concordance to the city of Mobile's wikipedia page, and derives all of it's name translations from the Mobile wiki page.

I think the correct approach here is to:
- Strip out the bunk concordances
- Remove "Mobile" names

The "USA" name is actually okay for this place, but not ideal for certain use cases, I'm sure :)
I'd like to keep the "USA" names, since they're used to reference the neighbourhood.. thoughts? how does a "USA" neighbourhood impact Pelias?

**Comment by missinglink** [comment]
Oh yeah that all sounds good.

Of course we don't love USA neighbourhoods but that's just the way the world is :)

**Comment by missinglink** [comment]
More generally speaking we'd ideally like to have the full name 'University of South Alabama' as althe preferred name and abbreviations as a secondary name or label, but I think that's your policy already right?

**Comment by stepps00** [comment]
Going to close this out in preference of #103. I've moved the commits from this PR to that new PR, and added more changes to fix whosonfirst-data/whosonfirst-data#1959.

**Pull request closed without merging**
