### PR TITLE
Add cessation date and mark San Francisco, Minnesota ghost town as non-current

### PR DESCRIPTION
**Pull request by orangejulius**
Updating `data/172/946/250/7/1729462507.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Closes https://github.com/whosonfirst-data/whosonfirst-data/issues/1987

### CODE REVIEW

**Comment by orangejulius** [comment]
Sorry about the noise, #117 and #116 were inadvertently created as no-op PRs, I think WriteField was a bit confused.

**Comment by nvkelso** [comment]
Please also edit to add as @thisisaaronland suggested in the related issue:

> wof:concordances.wd:id=Q7413896

**Comment by orangejulius** [comment]
Ok, concordance added in c424b49. The concordance editor in Writefield didn't seem to work so I just edited it manually. The JSON is valid, and I think it's correct.

**Comment by nvkelso** [comment]
Writefield is mostly useful to get the correct timestamp in there ;)

**Comment by nvkelso** [comment]
LGTM but @stepps00 to give it final once over please.

**Comment by stepps00** [comment]
Looks good - thanks @orangejulius !

**Pull request merged**
