### PR TITLE
Update Place Bar Code

### PR DESCRIPTION
**Pull request by stepps00**
Updating `data/112/599/567/1/1125995671.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by stepps00** [comment]
This place doesn't exist.. deprecating.

**Number of records updated**: 1

**Review by nvkelso — APPROVED** [review]
Approved. Looks like a junk locality import.

For reference, USPS says to NOT call the related zipcode by that name: https://codigo-postal.co/en-us/usa/zip/55172/

**Comment by stepps00** [comment]
Nice - also noticed WOF doesn't store this name in the postal locality fields https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-postalcode-us/master/data/554/729/045/554729045.geojson

**Comment by nvkelso** [comment]
We only hand curated a few of the "don't use this locality name" examples, IIRC?

**Comment by stepps00** [comment]
Yeah, I believe the those hand-curated values were stored in the `"mz:postal_locality_funky"` property.

More info here: https://github.com/whosonfirst-data/whosonfirst-data-postalcode-us/pull/5

**Pull request merged**
